spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/icecmspro?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: 23339097@qq.com # 发送人邮箱
    password: gsagrtgbwgicbhci # 邮箱授权码(上面获取到的)
    host: smtp.qq.com # 邮件服务器,163邮箱就是smtp.163.com
    protocol: smtp # 协议，可以不配，默认就是这个
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  #  mybatis-plus??sql??
  # configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/ttice/mapper/xml/*.xml
server:
  port: 8181
  #  ??ssh https
#  ssl:
#    key-store: classpath:Myssh.pfx
#    key-store-password: ko674hz8x35
#    key-store-type: PKCS12
